server:
  servlet:
    context-path: /api-greenscore-0
spring:
  data:
    mongodb:
#      uri: ${confpj.proprietes.utilisateur.mongodb.uri}&appName=${spring.application.name}
      uri: ${confpj.proprietes.utilisateur.mongodb.uri}
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE