# TODO DDC : check if all is ok with last version 3.1.0 (generation, ...).
# if no ok, try with 3.0.3
openapi: 3.1.0
info:
  title: GreenScore API specification
  description: |-
    Here is an API for GreenScore evaluation (from `API Thinking` organization) that allows some operations on :
    - rules definitions
    - score evaluation configuration
    - score evaluation process
  termsOfService: https://github.com/API-Green-Score/APIGreenScore
  contact:
    name: API GreenScore team
    url: https://github.com/API-Green-Score/APIGreenScore/discussions
  license:
    name: GPL 3.0
    url: https://github.com/API-Green-Score/APIGreenScore/blob/main/LICENCE.md
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about Api Green Score
  url: https://github.com/API-Green-Score/APIGreenScore?tab=readme-ov-file#api-green-score
servers:
  - url: https://localhost/api/v0
    description: Local server
tags:
  - name: rule
    description: Everything about available rules
    externalDocs:
      description: All about rules specification
      url: https://github.com/API-Green-Score/APIGreenScore?tab=readme-ov-file#api-lifecycle
  - name: score configuration
    description: Everything about grid score configuration
    externalDocs:
      description: https://www.collectif-api-thinking.com/assets/deliverables/worksites/48_CAT_Sustainable_API_GreenScore_V1-2.xlsx
      url: http://swagger.io
  - name: score evaluation
    description: Everything about grid score evaluation results and data history
paths:
  /rules:
    get:
      tags:
        - rule
      summary: Get all available rules
      description: Get all available rules with pagination and sorted by ruleId
      operationId: getRules
      parameters:
        - name: page
          in: query
          description: Zero-based page index
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rule'
  /rules/{ruleId}:
    get:
      tags:
        - rule
      summary: Get rule by ID
      description: get a single rule
      operationId: getRuleById
      parameters:
        - name: ruleId
          in: path
          description: ID of rule to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rule'
        '400':
          description: Invalid ID supplied
        '404':
          description: Rule not found
  /global_configuration:
    get:
      tags:
        - score configuration
      summary: Get global configuration data
      description: Get all data about global configuration of evaluation grid (table notes, section weigths, global note)
      operationId: getGlobalConfiguration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalConfiguration'
components:
  schemas:
    Rule:
      type: object
      properties:
        id:
          type: string
          description: Rule identifier
        section:
          type: string
          description: Rule section
        itemsAnalyzed:
          type: string
          description: Items analyzed by the rule
        description:
          type: string
          description: Rule description
        sectionWeight:
          type: number
          description: Rule weight in section
        totalWeight:
          type: number
          description: Total rule weight regarding all rules weight
        points:
          type: number
          description: Rule points regarding all rules
        evaluation:
          type: boolean
          description: True if rule has positive evaluation, false otherwise
        score:
          type: number
          description: Rule score infered from evaluation and points
        comment:
          type: string
          description: Evaluation comment for rule
        creationDate:
          type: string
          format: date-time
          description: Rule creation date
    GlobalConfiguration:
      type: object
      properties:
        globalNote:
          type: number
          description: The global note to be distributed over all enabled rules
        sections:
          type: array
          items:
            $ref: '#/components/schemas/Section'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    Section:
      type: object
      properties:
        name:
          type: string
          description: Section name
        weight:
          type: number
          description: Section weight
    Category:
      type: object
      properties:
        letter:
          type: string
          description: Category letter
        name:
          type: string
          description: Category name
        rangeMin:
          type: number
          description : the range minimum value for the category
        rangeMax:
          type: number
          description : the range maximum value for the category
